### PR TITLE
Fix typo in README.md

### PR DESCRIPTION
**Pull request by pajlada**
Just saw a little typo in the README as I was scrolling by

No PR too small!

### CODE REVIEW

**Comment by fzyzcjy** [comment]
Thanks! btw curious why are there so many ❤️ and 🚀 in 10 minutes?

**Comment by fzyzcjy** [comment]
@all-contributor please add pajlada for doc

**Comment by fzyzcjy** [comment]
@all-contributors please add pajlada for doc

**Comment by pajlada** [comment]
> Thanks! btw curious why are there so many heart and rocket in 10 minutes?

My group of friends who initially shared this repo with me saw the PR I made and showed their support for the repo :heart:

**Comment by fzyzcjy** [comment]
@pajlada I see :)

**Pull request merged**
